# Generated by Django 4.2.23 on 2025-09-08 03:46

from django.db import migrations, models
import django.utils.timezone
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/')),
                ('script', models.TextField(blank=True, help_text='Put ad script (AdSense) here if not using image')),
                ('position', models.CharField(choices=[('home_banner', 'Home banner'), ('sidebar_1', 'Sidebar 1')], default='home_banner', max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('post_type', models.CharField(choices=[('article', 'Article'), ('review', 'Review'), ('guide', 'Guide')], default='article', max_length=20)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('excerpt', models.TextField(blank=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Date/time shown on the site. You can edit this in the admin.', null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='TopPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('subtitle', models.CharField(blank=True, max_length=250)),
                ('price_text', models.CharField(blank=True, max_length=80)),
                ('cta_text', models.CharField(default='Buy Now', max_length=40)),
                ('cta_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='top_picks/')),
                ('active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
    ]
